#!/usr/bin/env bash

set -x

cd "$HOME" || exit

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    echo "Updating homebrew bundles"
    cd "$HOME" && brew doctor && brew bundle
else
    # [ ! -z "$sudo" ] && echo "Updating system package requires you pass"
    sudo apt-get update 
    sudo apt-get install -y `cat $HOME/Aptfile`
    sudo curl -sfLo /usr/local/bin/nvim \
        https://github.com/neovim/neovim/releases/download/v0.4.3/nvim.appimage
    sudo chmod +x /usr/local/bin/nvim
    if ! command -v antibody >/dev/null 2>&1; then
        curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin
    fi
    curl https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz | tar x
    ln -s node-v12.16.1-linux-x64 node
fi
# go
go get golang.org/x/tools/gopls@latest
# node
sudo npm install -g n
sudo n stable
# fzf
if [ -d "~/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    # TODO: copy ky beinding from the install script
    ~/.fzf/install --no-key-bindings --no-completion --no-update-rc --no-bash --no-fish --no-zsh
fi
# neovim's plug manager
if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
	curl -sfLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
python3 /tmp/get-pip.py
python3 -m pip install --user neovim
rm /tmp/get-pip.py
sudo npm install -g neovim 
sudo npm install -g how-2

curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

# Running neovim to update its plugins
nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+GoInstallBinaries' '+qall'

# tmux plugins update
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    mkdir -p "$HOME/.tmux/plugins"
    # installing tmux-plugin-manager and plugins
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    "$HOME"/.tmux/plugins/tpm/bin/install_plugins
else
    # updating tpm and plugins
    cd "$HOME/.tmux/plugins/tpm" || git pull -p
    cd "$HOME" || "$HOME"/.tmux/plugins/tpm/bin/update_plugins all
fi
# termino
tic "$HOME/.terminfo/xterm-256color-italic.terminfo"
# changing the shell to zsh for interactive sessions only
case $- in
  *) echo "Running in a script, not changing default shell"
     ;;
  *i*) echo ">>> Please enter you password to make zsh your default shell."
    chsh -s "$(command -v zsh)" || echo "*** Failed to chsh, please run it manually"  
    ;;  
esac
