#!/bin/bash
cd "$HOME" || exit
AFIDE="$HOME/.afide"

system_type=$(uname -s)

sudo=$(command -v sudo)

if [ "$system_type" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    echo "Updating homebrew bundles"
    cd "$HOME" && brew doctor && brew bundle --global
else
    $sudo apt-get update 
    $sudo apt-get install -y --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
    $sudo apt-get install tmux neovim zsh direnv
    curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
    # pyenv 
    [ ! -d $HOME/.pyenv ] && curl https://pyenv.run | zsh
    [ ! -d $HOME/.pyenv/plugins/pyenv-virtualenv ] && \
        git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
fi
zsh $HOME/.yadm/pyenv_bootstrap
# neovim plugins
if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
	curl -sfLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'

# Bootstrap tmux
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    mkdir -p "$HOME/.tmux/plugins"
    # installing tmux-plugin-manager and plugins
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    "$HOME"/.tmux/plugins/tpm/bin/install_plugins
else
    # updating tpm and plugins
    cd "$HOME/.tmux/plugins/tpm"
    git pull -p
    cd "$HOME"
    "$HOME"/.tmux/plugins/tpm/bin/update_plugins all
fi
# termino
tic "$HOME/.terminfo/xterm-256color-italic.terminfo"
