name: darwin_test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Get yadm and install the files
      run: |
        brew install git yadm
        yadm clone --no-bootstrap https://github.com/$GITHUB_REPOSITORY
        ~/.config/yadm/bootstrap
        yadm list
        nvim -es +checkhealth
