name: unbuntu_test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get yadm and git
      run: |
        sudo apt-get install git yadm
    - name: Clone the dot files
      run: |
        yadm clone --no-bootstrap https://github.com/$GITHUB_REPOSITORY
    - name: Run bootstrap
      run: |
        yadm bootstrap
    - name: Test neovim installation
      run: |
        nvim -es +checkhealth
