name: unbuntu_test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get yadm
      run: |
        apt-get update && apt-get install yadm
    - name: Clone the dot files
      run: |
        ./yadm clone --bootstrap https://github.com/$GITHUB_REPOSITORY
    - name: Test neovim installation
      run: |
        nvim -es +checkhealth
