name: unbuntu_test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get yadm
      run: |
        curl -fLo yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x yadm
    - name: Clone the dot files
      run: |
        ./yadm clone --no-bootstrap https://github.com/$GITHUB_REPOSITORY
    - name: Run bootstrap
      run: |
        ./yadm bootstrap
    - name: Test neovim installation
      run: |
        nvim -es +checkhealth
